CREATE TABLE system_expenses (
    id BIGINT NOT NULL AUTO_INCREMENT,
    description VARCHAR(180) NOT NULL,
    vendor VARCHAR(150) NULL,
    category VARCHAR(40) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    currency VARCHAR(5) NOT NULL,
    incurred_on DATE NOT NULL,
    payment_reference VARCHAR(120) NULL,
    notes TEXT NULL,
    recurring BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'POSTED',
    created_by VARCHAR(80) NOT NULL,
    updated_by VARCHAR(80) NOT NULL,
    voided_by VARCHAR(80) NULL,
    void_reason VARCHAR(300) NULL,
    voided_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_system_expense_month_currency_status (incurred_on, currency, status),
    KEY idx_system_expense_category_month (category, incurred_on),
    KEY idx_system_expense_created_at (created_at),
    CONSTRAINT chk_system_expense_amount CHECK (amount > 0)
);
