CREATE TABLE software_releases (
    id BIGINT NOT NULL AUTO_INCREMENT,
    platform VARCHAR(20) NOT NULL,
    package_type VARCHAR(30) NOT NULL,
    version VARCHAR(50) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    release_notes TEXT NULL,
    minimum_requirements VARCHAR(500) NULL,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NULL,
    file_size BIGINT NOT NULL,
    sha256_checksum CHAR(64) NOT NULL,
    published BIT(1) NOT NULL DEFAULT b'0',
    latest_release BIT(1) NOT NULL DEFAULT b'0',
    download_count BIGINT NOT NULL DEFAULT 0,
    uploaded_by VARCHAR(120) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    published_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_software_release_stored_file (stored_file_name),
    KEY idx_software_release_public (published, platform, latest_release, created_at),
    KEY idx_software_release_version (platform, package_type, version)
);
