ALTER TABLE branches
    MODIFY COLUMN module_type ENUM('SHOP_MODULE','GAS_MODULE','RESTAURANT_MODULE','FUEL_MODULE') NOT NULL;

ALTER TABLE tenant_enabled_modules
    MODIFY COLUMN module ENUM('SHOP_MODULE','GAS_MODULE','RESTAURANT_MODULE','FUEL_MODULE') NOT NULL;
