package com.retailzw.service;

import com.retailzw.enums.CurrencyCode;
import com.retailzw.model.*;
import com.retailzw.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.OptimisticLockingFailureException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
public class RetailExpenseService {
    private static final Set<String> PAYMENT_METHODS=Set.of("CASH","ECOCASH","ONEMONEY","INNBUCKS","CARD","SWIPE","ZIPIT","BANK_TRANSFER");
    private final RetailExpenseRepository expenses; private final BranchRepository branches; private final AuditLogRepository audit;
    public record Command(Long branchId,String description,String vendor,RetailExpense.Category category,BigDecimal amount,CurrencyCode currency,String paymentMethod,String paymentReference,LocalDate incurredOn,String notes){}
    @Transactional public RetailExpense create(Long tenant,Long user,Command command){validate(tenant,command);var e=RetailExpense.builder().tenantId(tenant).branchId(command.branchId()).expenseNumber(number(command.branchId())).description(clean(command.description())).vendor(optional(command.vendor())).category(command.category()).amount(command.amount().setScale(2,java.math.RoundingMode.HALF_UP)).currency(command.currency()).paymentMethod(clean(command.paymentMethod()).toUpperCase(Locale.ROOT)).paymentReference(optional(command.paymentReference())).incurredOn(command.incurredOn()).notes(optional(command.notes())).createdBy(user).updatedBy(user).build();e=expenses.save(e);log(e,"RETAIL_EXPENSE_CREATED",user,null);return e;}
    @Transactional public RetailExpense update(Long tenant,Long user,Long id,long version,Command command){validate(tenant,command);var e=owned(tenant,id);if(e.getStatus()==RetailExpense.Status.VOIDED)throw new IllegalArgumentException("Voided expenses cannot be edited.");if(e.getVersion()!=version)throw new OptimisticLockingFailureException("This expense was updated by another user. Refresh and try again.");String before=e.getDescription()+" | "+e.getCurrency()+" "+e.getAmount();e.setBranchId(command.branchId());e.setDescription(clean(command.description()));e.setVendor(optional(command.vendor()));e.setCategory(command.category());e.setAmount(command.amount().setScale(2,java.math.RoundingMode.HALF_UP));e.setCurrency(command.currency());e.setPaymentMethod(clean(command.paymentMethod()).toUpperCase(Locale.ROOT));e.setPaymentReference(optional(command.paymentReference()));e.setIncurredOn(command.incurredOn());e.setNotes(optional(command.notes()));e.setUpdatedBy(user);e=expenses.save(e);log(e,"RETAIL_EXPENSE_UPDATED",user,before);return e;}
    @Transactional public void voidExpense(Long tenant,Long user,Long id,long version,String reason){var e=owned(tenant,id);if(e.getStatus()==RetailExpense.Status.VOIDED)throw new IllegalArgumentException("Expense is already voided.");if(e.getVersion()!=version)throw new OptimisticLockingFailureException("This expense was updated by another user. Refresh and try again.");if(reason==null||reason.strip().length()<3||reason.strip().length()>300)throw new IllegalArgumentException("Provide a void reason between 3 and 300 characters.");e.setStatus(RetailExpense.Status.VOIDED);e.setVoidReason(reason.strip());e.setVoidedBy(user);e.setVoidedAt(LocalDateTime.now());e.setUpdatedBy(user);expenses.save(e);log(e,"RETAIL_EXPENSE_VOIDED",user,reason.strip());}
    public RetailExpense owned(Long tenant,Long id){return expenses.findByIdAndTenantId(id,tenant).orElseThrow(()->new IllegalArgumentException("Expense not found."));}
    private void validate(Long tenant,Command c){if(c.branchId()==null||branches.findById(c.branchId()).filter(b->b.getTenantId().equals(tenant)&&Boolean.TRUE.equals(b.getIsActive())).isEmpty())throw new IllegalArgumentException("Select an active branch belonging to this shop.");if(c.description()==null||c.description().strip().length()<3||c.description().strip().length()>180)throw new IllegalArgumentException("Description must be 3–180 characters.");if(c.category()==null||c.currency()==null)throw new IllegalArgumentException("Category and currency are required.");if(c.amount()==null||c.amount().compareTo(BigDecimal.ZERO)<=0||c.amount().scale()>2)throw new IllegalArgumentException("Amount must be greater than zero with at most 2 decimal places.");if(c.incurredOn()==null||c.incurredOn().isAfter(LocalDate.now()))throw new IllegalArgumentException("Expense date is required and cannot be in the future.");String method=c.paymentMethod()==null?null:c.paymentMethod().strip().toUpperCase(Locale.ROOT);if(method==null||!PAYMENT_METHODS.contains(method))throw new IllegalArgumentException("Select a valid payment method.");if(length(c.vendor())>150||length(c.paymentReference())>120||length(c.notes())>2000)throw new IllegalArgumentException("One or more fields exceed their allowed length.");}
    private String number(Long branch){return "EXP-"+branch+"-"+System.currentTimeMillis()+"-"+UUID.randomUUID().toString().substring(0,6).toUpperCase(Locale.ROOT);}
    private void log(RetailExpense e,String action,Long user,String before){audit.save(AuditLog.builder().tenantId(e.getTenantId()).branchId(e.getBranchId()).userId(user).action(action).entityType("RETAIL_EXPENSE").entityId(e.getId()).entityRef(e.getExpenseNumber()).beforeData(before==null?null:"{\"summary\":\""+json(before)+"\"}").afterData("{\"status\":\""+e.getStatus()+"\",\"amount\":\""+e.getAmount()+"\",\"currency\":\""+e.getCurrency()+"\"}").build());}
    private String json(String s){return s.replace("\\","\\\\").replace("\"","\\\"");} private int length(String s){return s==null?0:s.length();} private String clean(String s){return s==null?"":s.strip();} private String optional(String s){return s==null||s.isBlank()?null:s.strip();}
}
